apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mh276gefb-go
  janus-idp.io/tekton: mh276gefb-go
  backstage.io/kubernetes-id: mh276gefb-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mh276gefb-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
