apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mh276gefb-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mh276gefb-go 
  name: mh276gefb-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mh276gefb-go 
